#Celery config
CELERY_USERNAME = ""
CELERY_PASSWORD = ""
CELERY_SERVER = "127.0.0.1"

#Directory configurations
NFS_SERVER_IP=""
NFS_DIRECTORY=""

LOCAL_MOUNT_DIRECTORY=""
XMRG_DATA_DIRECTORY = ""
LOGFILE_DIRECTORY = ""

REQUEST_DIRECTORY = ""
BOUNDARY_DIRECTORY = ""
LOGFILE_DIRECTORY = ""
DATA_DIRECTORY = ""
RESULTS_DIRECTORY = ""

#Data Processing flags
WORKER_COUNT=4
DELETE_SOURCE_FILE=True
DELETE_COMPRESSED_SOURCE_FILE=True
SAVE_ALL_PRECIP_VALUES=True

#This flag will append the other files created during the XMRG processing.
ADD_DEBUG_FILES = False
MAILHOST=""
FROMADDR=""
USER=""
PASSWORD=""
PORT=465
